# Config file for automatic testing at travis-ci.org

sudo: required

dist: trusty

language: generic

services:
  - docker

matrix:
  include:
    - name: gcc
      env: CXX=g++ CC=gcc
    - name: gcc-7
      env: CXX=g++-7 CC=gcc-7
    - name: clang-3.8
      env: CXX=clang++-3.8 CC=clang-3.8
    - name: clang-6.0
      env: CXX=clang++-6.0 CC=clang-6.0
    - name: Bazel 0.23.2
      install:
        - docker pull l.gcr.io/google/bazel:0.23.2
      script:
        - docker run -v `pwd`:/PI -w /PI l.gcr.io/google/bazel:0.23.2 test //proto/tests:pi_proto_tests //proto/tests:pi_proto_server_tests

install:
  - docker build -t pi --build-arg IMAGE_TYPE=test --build-arg CC=$CC --build-arg CXX=$CXX -f Dockerfile.bmv2 .

script:
  - docker run -w /PI pi make check -j2
  - docker run -w /PI pi ./tools/check_style.sh
