# Config file for automatic testing at travis-ci.org

sudo: required

dist: trusty

language: generic

services:
  - docker

matrix:
  include:
    - env: CXX=g++ CC=gcc
    - env: CXX=g++-6 CC=gcc-6
    - env: CXX=clang++-3.8 CC=clang-3.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

install:
  - docker build -t pi --build-arg IMAGE_TYPE=test --build-arg CC=$CC --build-arg CXX=$CXX -f Dockerfile.bmv2 .

script:
  - docker run -w /PI pi make check -j2
  - docker run -w /PI pi ./tools/check_style.sh
