# Config file for automatic testing at travis-ci.org

sudo: required

dist: trusty

language: generic

services:
  - docker

matrix:
  include:
    - env: CXX=g++ CC=gcc
    - env: CXX=clang++-3.8 CC=clang-3.8

install:
  - docker build -t pi .

script:
  - docker run -w /PI pi make check -j2
  - ./tools/check_style.sh
