# SPDX-FileCopyrightText: 2018 Barefoot Networks, Inc.
#
# SPDX-License-Identifier: Apache-2.0

filegroup(
    name = "exported_testdata",
    srcs = glob([
        "testdata/*.txt",
        "testdata/*.json",
    ]),
    visibility = ["//:__subpackages__"],
)
