package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "pifecpp",
    srcs = ["src/tables.cpp"],
    hdrs = ["PI/frontends/cpp/tables.h"],
    includes = ["."],
    deps = ["//:pi"],
)
